version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    depends_on:
      - redis
    volumes:
      - ./src:/app/src:ro
      - ./.env:/app/.env:ro
    environment:
      - NODE_ENV=development
      - LOG_LEVEL=debug
      - REDIS_URL=redis://redis:6379

  redis:
    image: redis:7.2-alpine
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data

volumes:
  redis_data: